[package]
name = "queue-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "2.3.1"
bincode = "1.3.3"
anyhow = "1.0.75"
serde = { version = "1.0.193", features = ["derive"] }